### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by RollRim** [DaedalusGame/Modular-Diversity#64]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  SimpleDifficulty ASM (SimpleDifficulty-1.12.2-0.3.9.jar)
  AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  TenshiCore (TenshiLib-1.12.2-1.2.4.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  clothesline-hooks (clothesline-hooks-1.12.2-0.0.1.2.jar)
  Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.7.jar)
  AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.3.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 9/8/22 7:43 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: hellfirepvp/modularmachinery/common/crafting/ComponentType$ComponentRegistryEvent
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:612)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: hellfirepvp/modularmachinery/common/crafting/ComponentType$ComponentRegistryEvent
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 36 more
Caused by: java.lang.ClassNotFoundException: hellfirepvp.modularmachinery.common.crafting.ComponentType$ComponentRegistryEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 536410136 bytes (511 MB) / 1140850688 bytes (1088 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 90 mods loaded, 90 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                     | Version                 | Source                                        | Signature                                |
	|:----- |:---------------------- |:----------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft              | 1.12.2                  | minecraft.jar                                 | None                                     |
	| LC    | mcp                    | 9.42                    | minecraft.jar                                 | None                                     |
	| LC    | FML                    | 8.0.99.99               | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                  | 14.23.5.2860            | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | clothesline-hooks      | 1.12.2-0.0.1.2          | minecraft.jar                                 | None                                     |
	| LC    | alcatrazcore           | 1.0.4                   | alcatrazcore-1.0.4.jar                        | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LC    | applecore              | 3.4.0                   | AppleCore-mc1.12.2-3.4.0.jar                  | None                                     |
	| LC    | baubles                | 1.5.2                   | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LC    | crafttweaker           | 4.1.20                  | CraftTweaker2-1.12-4.1.20.674.jar             | None                                     |
	| LC    | astralsorcery          | 1.10.27                 | astralsorcery-1.12.2-1.10.27.jar              | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LC    | jei                    | 4.16.1.301              | jei_1.12.2-4.16.1.301.jar                     | None                                     |
	| LC    | athenaeum              | 1.12.2-1.19.5           | athenaeum-1.12.2-1.19.5.jar                   | None                                     |
	| LC    | autoreglib             | 1.3-32                  | AutoRegLib-1.3-32.jar                         | None                                     |
	| LC    | base                   | 3.14.0                  | base-1.12.2-3.14.0.jar                        | None                                     |
	| LC    | forgelin               | 1.8.4                   | Forgelin-1.8.4.jar                            | None                                     |
	| LC    | betterfoliage          | 2.3.1                   | BetterFoliage-MC1.12-2.3.1.jar                | None                                     |
	| LC    | betterquesting         | 3.5.329                 | BetterQuesting-3.5.329 (1).jar                | None                                     |
	| LC    | bookshelf              | 2.3.590                 | Bookshelf-1.12.2-2.3.590.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | mantle                 | 1.12-1.3.3.55           | Mantle-1.12-1.3.3.55 (2).jar                  | None                                     |
	| LC    | tconstruct             | 1.12.2-2.13.0.183       | TConstruct-1.12.2-2.13.0.183 (2).jar          | None                                     |
	| LC    | contenttweaker         | 1.12.2-4.10.0           | ContentTweaker-1.12.2-4.10.0.jar              | None                                     |
	| LC    | coralreef              | 2.0                     | CoralReef-2.5-1.12.2.jar                      | None                                     |
	| LC    | extendedrenderer       | v1.0                    | coroutil-1.12.1-1.2.37 (1).jar                | None                                     |
	| LC    | coroutil               | 1.12.1-1.2.37           | coroutil-1.12.1-1.2.37 (1).jar                | None                                     |
	| LC    | configmod              | v1.0                    | coroutil-1.12.1-1.2.37 (1).jar                | None                                     |
	| LC    | ctgui                  | 1.0.0                   | CraftTweaker2-1.12-4.1.20.674.jar             | None                                     |
	| LC    | crafttweakerjei        | 2.0.3                   | CraftTweaker2-1.12-4.1.20.674.jar             | None                                     |
	| LC    | deadlyworld            | 1.1.1_for_mc1.12.2      | deadlyworld-1.1.1_for_mc1.12.2 (1).jar        | None                                     |
	| LC    | dropt                  | 1.12.2-1.19.3           | dropt-1.12.2-1.19.3.jar                       | None                                     |
	| LC    | sereneseasons          | 1.2.18                  | SereneSeasons-1.12.2-1.2.18-universal.jar     | None                                     |
	| LC    | orelib                 | 3.6.0.1                 | OreLib-1.12.2-3.6.0.1.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LC    | dsurround              | @VERSION@               | DynamicSurroundings-1.12.2-3.6.3.jar          | None                                     |
	| LC    | dynamictrees           | 1.12.2-0.9.29           | DynamicTrees-1.12.2-0.9.29.jar                | None                                     |
	| LC    | thaumcraft             | 6.1.BETA26              | Thaumcraft-1.12.2-6.1.BETA26.jar              | None                                     |
	| LC    | dynamictreestc         | 1.12.2-1.4.2            | DynamicTreesTC-1.12.2-1.4.2.jar               | None                                     |
	| LC    | dynamictreestconstruct | 1.12.2-1.2.7            | DynamicTreesTinkersConstruct-1.12.2-1.2.7.jar | None                                     |
	| LC    | earthworks             | 1.3.4.3                 | Earthworks-1.12-1.3.6.jar                     | None                                     |
	| LC    | mysticalmechanics      | 0.18                    | Mystical+Mechanics-0.18 (1).jar               | None                                     |
	| LC    | embers                 | 1.19                    | EmbersRekindled-1.19.jar                      | None                                     |
	| LC    | firstaid               | 1.6.20                  | firstaid-1.6.20.jar                           | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| LC    | globalgamerules        | 2.2                     | GlobalGameRules-1.12.2-2.2.7.jar              | None                                     |
	| LC    | harvesttweaks          | 1.12-0.1.6.DEV.9459cd5  | HarvestTweaks-1.12-0.1.6.jar                  | None                                     |
	| LC    | waila                  | 1.8.26                  | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| LC    | ichunutil              | 7.2.2                   | iChunUtil-1.12.2-7.2.2 (1).jar                | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | improvedmobs           | 1.6.10                  | ImprovedMobs-1.12.2-1.6.10.jar                | None                                     |
	| LC    | jaopca                 | 1.12.2-2.3.0.0          | JAOPCA-1.12.2-2.3.0.0.jar                     | None                                     |
	| LC    | jarm                   | 1.1.2                   | Just+A+Raft+Mod-1.1.2.jar                     | None                                     |
	| LC    | jeresources            | 0.9.2.60                | JustEnoughResources-1.12.2-0.9.2.60.jar       | None                                     |
	| LC    | mtrm                   | 1.2.2.30                | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar    | None                                     |
	| LC    | mobamputation          | 7.0.0                   | MobAmputation-1.12.2-7.0.1 (1).jar            | None                                     |
	| LC    | mobdismemberment       | 7.0.0                   | MobDismemberment-1.12.2-7.0.0 (1).jar         | None                                     |
	| LC    | mobsunscreen           | 1.12.2-2.1.3            | mobsunscreen-1.12.2-2.1.3.jar                 | None                                     |
	| LC    | modnametooltip         | 1.10.1                  | modnametooltip_1.12.2-1.10.1.jar              | None                                     |
	| LC    | modularmachinery       | 1.11.1                  | modularmachinery-1.12.2-1.11.1.jar            | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LE    | modulardiversity       | 1.10                    | Modular+Diversity-1.10.jar                    | None                                     |
	| L     | rustichromia           | 0.9                     | Rustichromia-0.9.jar                          | None                                     |
	| L     | thaumicperiphery       | 0.3.1                   | thaumicperiphery-0.3.1.jar                    | None                                     |
	| L     | mystgears              | 1.1.7                   | mystgears-1.1.7 (1).jar                       | None                                     |
	| L     | noworldgen5you         | 1.0.6                   | NoWorldgen5You-1.12.2-1.0.6.jar               | None                                     |
	| L     | patchouli              | 1.0-23.6                | Patchouli-1.0-23.6 (1).jar                    | None                                     |
	| L     | soot                   | 1.10-hotfix             | Soot-1.10-hotfix.jar                          | None                                     |
	| L     | pewter                 | 1.4.3                   | Pewter-1.4.3.jar                              | None                                     |
	| L     | prodigytech            | 1.3.4                   | prodigytech-1.12.2-1.3.4.jar                  | None                                     |
	| L     | prodigymechanics       | 0.3                     | ProdigyMechanics-0.3.jar                      | None                                     |
	| L     | pyrotech               | 1.12.2-1.6.3            | pyrotech-1.12.2-1.6.3.jar                     | None                                     |
	| L     | rootsclassic           | 1.12.2-1.1.7            | RootsClassic-1.12.2-1.1.7.jar                 | None                                     |
	| L     | rotm                   | 1.1.4                   | rotm-1.12.2-1.1.4.jar                         | None                                     |
	| L     | simpledifficulty       | 0.3.9                   | SimpleDifficulty-1.12.2-0.3.9.jar             | None                                     |
	| L     | simplytea              | 1.6                     | simplytea-1.6.jar                             | None                                     |
	| L     | sinkorswim             | 1.0.0                   | Sink-1.0.0.jar                                | None                                     |
	| L     | bq_standard            | 3.4.173                 | StandardExpansion-3.4.173 (1).jar             | None                                     |
	| L     | tenshilib              | 1.2.4                   | TenshiLib-1.12.2-1.2.4.jar                    | None                                     |
	| L     | thaumicaugmentation    | 1.12.2-2.1.7            | ThaumicAugmentation-1.12.2-2.1.7.jar          | None                                     |
	| L     | thaumicjei             | 1.6.0                   | ThaumicJEI-1.12.2-1.6.0-27.jar                | None                                     |
	| L     | thaumic_mercy          | 0.2                     | ThaumicMercy-0.2.jar                          | None                                     |
	| L     | tcomplement            | 1.12.2-0.4.3            | TinkersComplement-1.12.2-0.4.3.jar            | None                                     |
	| L     | tinkersforging         | 1.1.4                   | tinkersforging-1.1.4.jar                      | None                                     |
	| L     | tinkersjei             | 1.2                     | tinkersjei-1.2.jar                            | None                                     |
	| L     | wailaharvestability    | 1.1.12                  | WailaHarvestability-mc1.12-1.1.12.jar         | None                                     |
	| L     | watercontrolextreme    | 1.0.0                   | WaterControlExtreme-1.0.2.jar                 | None                                     |
	| L     | weather2               | 1.12.1-2.6.12           | weather2-1.12.1-2.6.12 (1).jar                | None                                     |
	| L     | worleycaves            | 1.5.2                   | worleycaves-1.12.2-1.5.2.jar                  | None                                     |
	| L     | zombie_players         | 1.12.1-1.2.7            | zombie_players-1.12.1-1.2.7.jar               | None                                     |
	| L     | zombieawareness        | 1.12.1-1.11.16          | zombieawareness-1.12.1-1.11.16 (1).jar        | None                                     |
	| L     | clothesline            | 1.12.2-0.0.4.2          | clothesline-1.12.2-0.0.4.2-bundle.jar         | None                                     |
	| L     | llibrary               | 1.7.20                  | llibrary-1.7.20-1.12.2.jar                    | None                                     |
	| L     | rtg                    | 6.1.0.0-snapshot.1      | RTG-1.12.2-6.1.0.0-snapshot.1.jar             | None                                     |
	| L     | hookt                  | 1.12.2-1.1.0            | hookt-1.12.2-1.1.0 (1).jar                    | None                                     |
	| L     | hungeroverhaul         | 1.12.2-1.3.3.jenkins148 | HungerOverhaul-1.12.2-1.3.3.jenkins148.jar    | None                                     |
	| L     | wrapup                 | 1.12-1.1.3              | WrapUp-1.12-1.1.3.jar                         | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
SimpleDifficulty ASM (SimpleDifficulty-1.12.2-0.3.9.jar)
  com.charles445.simpledifficulty.asm.SimpleDifficultyASM
AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  
BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
TenshiCore (TenshiLib-1.12.2-1.2.4.jar)
  com.flemmli97.tenshilib.asm.ASMTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
clothesline-hooks (clothesline-hooks-1.12.2-0.0.1.2.jar)
  com.jamieswhiteshirt.clothesline.hooks.plugin.ClassTransformer
Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.7.jar)
  thecodex6824.thaumicaugmentation.core.TATransformer
AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
TransformLoader (DynamicSurroundings-1.12.2-3.6.3.jar)
  
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/harvesttweaks loaded Pulses: 
		- blocks (Enabled/Forced)
		- items (Enabled/Forced)
		- tconstruct (Enabled/Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.14761 Compatibility Profile Context 21.30.23.04 30.0.13023.4001
	OpenGlRenderer: Radeon RX 570 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12

**Comment by JukoiDev** [comment]
same, mod ain't updated

**Comment by TheFieryFalcon** [comment]
#53
